#!/usr/bin/env ruby

$stdout.sync = true

$LOAD_PATH.unshift File.expand_path("./lib", __dir__)

require "rubygems"
require "bundler/setup"

require_relative "lib/robot_chicken"

Bundler.require :default, ENV.fetch("RUBY_ENV", "development")

begin
  RobotChicken.run
rescue => e
  RobotChicken.logger.error e
  retry
end

at_exit do
  RobotChicken.logger.info "Exiting"
end
